// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using Pequi.Dominio.Entidades;

#nullable disable

namespace Pequi.Infra.Dados.EF
{
    public class ClienteConfiguration : IEntityTypeConfiguration<Cliente>
    {
        public void Configure(EntityTypeBuilder<Cliente> entity)
        {
            entity.Property(e => e.DataAtualizacao).HasColumnType("datetime");

            entity.Property(e => e.DataNascimento).HasColumnType("datetime");

            entity.Property(e => e.Email).HasMaxLength(50);

            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(100);
        }
    }
}
